---
title: "Getting started with LaTeX"
author: "A laboratory manual written by Duncan Hull at the University of Manchester"
date: "Last updated `r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: dullhunk/latex4year1
description: "A resource for getting started with LaTeX"
---

# Welcome {-}

Reading this LaTeX guide and doing the five exercises it contains will enable you to develop your written communication skills using LaTeX so that you can:

1. Create a simple document in pdf using LaTeX
1. Illustrate a document with figures and cross references
1. Typeset some mathematics
1. Share and collaborate on LaTeX documents using overleaf
1. Create a CV using LaTeX templates in overleaf

## Acknowledgements {-}
This document is a substantially revised version of earlier LaTeX lab manuals created by Ulrike Sattler, Graham Gough, Paul Waring, Toby Howard and Steve Pettifer. Thanks to everyone who has contributed or provided feedback.

## Improve this guide {-}
The source of this document is on github so if you have any comments or suggestions on how to improve it, you can [raise an issue](https://github.com/dullhunk/lateX4year1/issues) or [submit a pull request](https://github.com/dullhunk/LaTeX4year1/pulls).
